### ISSUE TITLE
Lockpick error v1.6

### ISSUE THREAD

**Issue by Nifelhein** [cont1nuity/new-openables-continued#10]
On 1.6 having a lockbox on yoru bag results in an error. Rogue lvl is above the necessary for this particular lockbox:

Rogue lvl 65 (lockpicking skill is the same as the lvl)
Item ID is 43622, Froststeel Lockbox qhich requires lockpicking (30)

Error  given by verbose mode:

> [12:21:11]  [NOP] ItemGetItem: itemID 186710 rejected by map use 
[12:21:12]  [NOP] ItemGetItem: itemID 186710 rejected by map use 
[12:21:12] BugSack: There's a bug in your soup! 
[12:21:21]  [NOP] ItemGetItem: itemID 186710 rejected by map use 
[12:21:41]  [NOP] ItemGetSpell: itemID 113558 spell Learning 
[12:21:41]  [NOP] ItemToUse: itemID 113558 count 1 prio 2 zone nil map nil aura nil source SPELL 
[12:21:41]  [NOP] ItemGetItem: itemID 186710 rejected by map use 
[12:21:41] BugSack: There's a bug in your soup!
>

And this is from bug grabber

> 18x NOP/nop-item.lua:105: attempt to call method 'GetText' (a nil value)
[string "@NOP/nop-item.lua"]:105: in function `ItemGetLockPattern'
[string "@NOP/nop-item.lua"]:127: in function `ItemGetPattern'
[string "@NOP/nop-item.lua"]:229: in function `ItemScan'
[string "@NOP/nop-item.lua"]:409: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>
Locals:
self = <table> {
 pickLockSpell = "Pick Lock"
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 QBQuestAccept = <function> defined @NOP/nop-quest.lua:268
 LOOT_SPEC = <function> defined @NOP/nop-events.lua:121
 ItemGetItem = <function> defined @NOP/nop-item.lua:64
 ButtonOnDragStop = <function> defined @NOP/nop-button.lua:186
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 ItemGetLockPattern = <function> defined @NOP/nop-item.lua:99
 ActionButton_ShowOverlayGlow = <function> defined @NOP/nop-button.lua:421
 QBAnchor = <function> defined @NOP/nop-quest.lua:71
 IsEnabled = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 SpellLoad = <function> defined @NOP/nop-core.lua:225
 ScheduleTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 QBButton = <function> defined @NOP/nop-quest.lua:88
 ProfileLoad = <function> defined @NOP/nop-profile.lua:25
 Zone = "Ahava's Garrison"
 PLAYER_LOGIN = <function> defined @NOP/nop-events.lua:140
 InitEvents = <function> defined @NOP/nop-events.lua:49
 ButtonReputation = <function> defined @NOP/nop-button.lua:121
 PrintTooltip = <function> defined @NOP/nop-core.lua:277
 ButtonHotKey = <function> defined @NOP/nop-button.lua:356
 ItemLoad = <function> defined @NOP/nop-core.lua:143
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 GetLinesFromTooltipData = <function> defined @NOP/nop-core.lua:112
 T_ITEMS = <table> {
 }
 OnEnable = <function> defined @NOP/nop-core.lua:98
 ButtonShow = <function> defined @NOP/nop-button.lua:315
 spellLoad = true
 ButtonOnEnter = <function> defined @NOP/nop-button.lua:135
 frameHiderB = NOP_HiderB {
 }
 T_DISENCHANT_ITEMS = <table> {
 }
 OnInitialize = <function> defined @NOP/nop-core.lua:88
 UnregisterAllEvents = <function> defined @SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 removekey = <function> defined @NOP/nop-core.lua:359
 itemLoad = true
 ActionButton_HideOverlayGlow = <function> defined @NOP/nop-button.lua:435
 QUEST_ACCEPTED = <function> defined @NOP/nop-events.lua:195
 ItemGetSpell = <function> defined @NOP/nop-item.lua:56
 QBOnLeave = <function> defined @NOP/nop-quest.lua:141
 GetName = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 ActionButton_GetOverlayGlow = <function> defined @NOP/nop-button.lua:413
 QBSkin = <function> defined @NOP/nop-quest.lua:264
 ButtonLoad = <function> defined @NOP/nop-button.lua:256
 ButtonReset = <function> defined @NOP/nop-button.lua:191
 PLAYER_LEVEL_UP = <function> defined @NOP/nop-events.lua:189
 Print = <function> defined @ElvUI_Libraries/Core/Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
 GetReputation = <function> defined @NOP/nop-core.lua:506
 GET_ITEM_INFO_RECEIVED = <function> defined @NOP/nop-events.lua:220
 ItemIsUnusable = <function> defined @NOP/nop-item.lua:250
 QBKeyBind = <function> defined @NOP/nop-quest.lua:168
 Profile = <function> defined @NOP/nop-core.lua:335
 ACTIONBAR_UPDATE_COOLDOWN = <function> defined @NOP/nop-events.lua:202
 UnregisterEvent = <function> defined @SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 SetDef

**Comment by cont1nuity** [comment]
Thank you. 
Please try the next alpha version, which should be available in the next minutes/hour.

**Comment by Nifelhein** [comment]
Downloaded alpha v1.6-2-g5ffabcc and got the followeing error:

```
3x NOP/nop-item.lua:105: bad argument #1 to 'match' (string expected, got table)
[string "=[C]"]: in function `match'
[string "@NOP/nop-item.lua"]:105: in function `ItemGetLockPattern'
[string "@NOP/nop-item.lua"]:127: in function `ItemGetPattern'
[string "@NOP/nop-item.lua"]:229: in function `ItemScan'
[string "@NOP/nop-item.lua"]:409: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = <table> {
 leftColor = <table> {
 }
 type = 0
 leftText = "Requires Lockpicking (30)"
 args = <table> {
 }
}
(*temporary) = "%d+"
(*temporary) = "string expected, got table"

```

**Comment by cont1nuity** [comment]
Thanks. Can you try with the next alpha as well please?
Made a bad paste mistake there :)

**Comment by Nifelhein** [comment]
Tested version NOP-v1.6a-1-gb192f0c, worked perfectly

**Comment by cont1nuity** [comment]
Thank you for verifying!
