### ISSUE TITLE
Cosmetic? error v1.6

### ISSUE THREAD

**Issue by BelegCufea** [cont1nuity/new-openables-continued#11]
Hello there :-)

I am getting error in version 1.6.

> Verbose
```
 [17:20]  [NOP] ItemShowNew: itemID 198129 Zone yes Priority 2 Stamp 469067.754 
 [17:20]  [NOP] itemID 198129 has red text in tooltip! Requires Dragon Isles Cooking (40) 
 [17:20]  [NOP] ItemShowNew: itemID 201458 Zone yes Priority 2 Stamp 469067.755 
 [17:20] BugSack: There's a bug in your soup!
```

> Bugsack (if u need more, I will post locales as well)
```
121x NOP/nop-item.lua:307: attempt to call method 'GetText' (a nil value)
[string "@NOP/nop-item.lua"]:309: in function `ItemIsUsable'
[string "@NOP/nop-item.lua"]:444: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

...
```

It is on [Aegis of Tyrhold](https://www.wowhead.com/item=201458/aegis-of-tyrhold). It may be due to it is cosmetic item, but I can't tell for sure.

Thanks for nice addon BTW.

**Comment by cont1nuity** [comment]
Thank you.
Please try the next alpha version. Should be up soon.

**Comment by BelegCufea** [comment]
Thank you for quick response.

Works like a charm. You can close the issue if u want.

Have a nice day!

**Comment by cont1nuity** [comment]
Thank you for reporting and verifying!
