### ISSUE TITLE
Masque support isn't working. I can't skin the button at all.

### ISSUE THREAD

**Issue by ZaViper** [cont1nuity/new-openables-continued#14]
I left a comment about this on the addon page at CurseForge back in April. You told me, "It requires a /reload to be active after the setting is enabled and works pretty fine on my end."

I responded back saying that I tired this and it didn't work. Doing a /reload after enabling the setting didn't work. New Openables doesn't show up on Masque list of addons for me to skin. I have tired doing a /reload after enabling, and disabling Masque support setting. I have also tired doing a /reload after enabling and disabling the skin button setting and nothing happens. I have also tired deleting the addon and all it's setting files from the WTF folder and reinstalling the addon fresh and that didn't work either.

Anyways, hoping to hear a response.

**Comment by cont1nuity** [comment]
NOP does not add own profile options to Masque but uses the default settings. There is no support for dedicated skin settings.

**Comment by ZaViper** [comment]
Hmmm. Alright, so I completely deleted everything New Openables again, and deleted everything Masque as well. No SavedVariables for both apps, a fresh install for both, and I'm still having the same issue. I don't know why you can see NOP on Masque, but I can't.

https://i.imgur.com/x9eyzck.png

**Comment by cont1nuity** [comment]
What do the following commands print in chat?
`/run print(NOP and NOP.masque)`
`/dump NOP_dev.AceDB.profile.masque`

**Comment by ZaViper** [comment]
`/run print(NOP and NOP.masque)` simply said "nil"

`/dump NOP_dev.AceDB.profile.masque` just says: 

`Dump: value=NOP_dev.AceDB.profile.masque`

**Comment by cont1nuity** [comment]
I needed to correct the second command. Can you retry this please?
I'll push an alpha version with some small adjustment to see if this improves things.

**Comment by ZaViper** [comment]
That worked! Thank you! I'm so stoked, I've lived without a skinned button for so long. haha

**Comment by cont1nuity** [comment]
Thanks for verifying :)
