### ISSUE TITLE
Whelpling Shadowflame Crest Fragments Issue

### ISSUE THREAD

**Issue by future-greg** [cont1nuity/new-openables-continued#17]
Whelpling Shadowflame Crest Fragments Issue are not popping up at 15 count, as they used to before, which would allow you to convert the crests. Previously did, however not sure if recent updates do not allow that functionality anymore.

**Comment by cont1nuity** [comment]
Works fine on my end. Ensure that you did not accidentally blacklisted it.
`/nop list`

**Comment by future-greg** [comment]
Whelp. You're right - seems like it was inadvertently blacklisted. I went ahead and did /nop list clear to get it working again, in case I had accidently BL'd anything else - good looking out.
