### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Fizgig1973** [cont1nuity/new-openables-continued#19]
Getting the following errors upon loading in Bugsack.

9x NOP/nop-data.lua:10: PRI_OPEN
[string "=[C]"]: in function `assert'
[string "@NOP/nop-data.lua"]:10: in main chunk

Locals:
(*temporary) = false
(*temporary) = "PRI_OPEN"

9x NOP/nop-button.lua:30: BUTTON_FRAME
[string "=[C]"]: in function `assert'
[string "@NOP/nop-button.lua"]:30: in main chunk

Locals:
(*temporary) = false
(*temporary) = "BUTTON_FRAME"

9x NOP/nop-profile.lua:14: T_CHECK
[string "=[C]"]: in function `assert'
[string "@NOP/nop-profile.lua"]:14: in main chunk

Locals:
(*temporary) = false
(*temporary) = "T_CHECK"

9x NOP/nop-events.lua:36: print
[string "=[C]"]: in function `assert'
[string "@NOP/nop-events.lua"]:36: in main chunk

Locals:
(*temporary) = false
(*temporary) = "print"

9x NOP/nop-core.lua:55: ARCHAELOGY_ANNOUNCE
[string "=[C]"]: in function `assert'
[string "@NOP/nop-core.lua"]:55: in main chunk

Locals:
(*temporary) = false
(*temporary) = "ARCHAELOGY_ANNOUNCE"

9x NOP/nop-item.lua:33: T_BAGS
[string "=[C]"]: in function `assert'
[string "@NOP/nop-item.lua"]:33: in main chunk

Locals:
(*temporary) = false
(*temporary) = "T_BAGS"

9x NOP/nop-slash.lua:26: T_CHECK
[string "=[C]"]: in function `assert'
[string "@NOP/nop-slash.lua"]:26: in main chunk

Locals:
(*temporary) = false
(*temporary) = "T_CHECK"

9x NOP/nop-quest.lua:33: print
[string "=[C]"]: in function `assert'
[string "@NOP/nop-quest.lua"]:33: in main chunk

Locals:
(*temporary) = false
(*temporary) = "print"

**Comment by cont1nuity** [comment]
That seems to be a follow-up error.
Please get BugSack and BugGrabber addons and post all NOP related errors.
You could try re-installing as well.

**Comment by Fizgig1973** [comment]
Those are multiple errors from Bugsack. 

And I have uninstalled, reinstalled.

**Comment by cont1nuity** [comment]
There seems to be at least one missing then, in nop-private.lua, that would cause the chain of the others.
What's your game version?

**Comment by Fizgig1973** [comment]
Sorry for the delay.  I disabled all addons except for New Openables and get the following error:

Message: Interface/AddOns/NOP/WagoAnalytics/Shim.lua:1: attempt to index global 'LibStub' (a nil value)
Time: Mon May  6 09:09:35 2024
Count: 1
Stack: Interface/AddOns/NOP/WagoAnalytics/Shim.lua:1: attempt to index global 'LibStub' (a nil value)
[string "@Interface/AddOns/NOP/WagoAnalytics/Shim.lua"]:1: in main chunk

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LibStub' (a nil value)"


I had no problems when loading with other addons until I came to Caedron Wardrobe. When loaded with Caedron Wardrobe I get the following:


1x ...eCaerdonWardrobe/libs/WagoAnalytics/Shim.lua:10: attempt to call method 'Register' (a nil value)
[string "@CaerdonWardrobe/libs/WagoAnalytics/Shim.lua"]:10: in function `Register'
[string "@NOP/nop-private.lua"]:31: in main chunk

Locals:
self = <table> {
 RegisterAddon = <function> defined @CaerdonWardrobe/libs/WagoAnalytics/Shim.lua:25
 RegisterAddOn = <function> defined @CaerdonWardrobe/libs/WagoAnalytics/Shim.lua:25
 Register = <function> defined @CaerdonWardrobe/libs/WagoAnalytics/Shim.lua:7
}
wagoID = "RBKpYOGE"
WagoAnalytics = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "RBKpYOGE"
(*temporary) = "attempt to call method 'Register' (a nil value)"

**Comment by Fizgig1973** [comment]
I do not. 

It looks like Caedron Wardrobe and Mythic Dungeon Tools have them included though.

**Comment by cont1nuity** [comment]
They likely have the Shim embedded, same as NOP. Could you try the latest alpha version with and without these addons?

**Comment by cont1nuity** [comment]
Looks like it. Seems like the embed is broken or outdated. I cannot help you there, unfortunately.

**Comment by Fizgig1973** [comment]
Not a problem. Thank you for all your assistance, and for keeping NOP alive.

**Comment by cont1nuity** [comment]
Trying my best over here :)

**Comment by bloerwald** [comment]
FYI: You seem to not have tagged a new release yet.
