### ISSUE TITLE
Treatise Handling Suggestion

### ISSUE THREAD

**Issue by Sildris** [cont1nuity/new-openables-continued#24]
Thanks for maintaining this addon, greatly appreciate your work. 

Would it be possible to improve how treatise (e.g.Algari Treatise of Herbalism) function so that they're automatically blacklisted if they've been learned for the week?

**Comment by cont1nuity** [comment]
I'll have a look. I likely need to rework quite a bit to make this happen.

**Comment by cont1nuity** [comment]
Should work in the latest alpha.
