### ISSUE TITLE
Rattling Bag o' Gold

### ISSUE THREAD

**Issue by whoiskevinrich** [cont1nuity/new-openables-continued#25]
Missing Item:

https://www.wowhead.com/item=225249/rattling-bag-o-gold

**Comment by cont1nuity** [comment]
Please clean up indentation.
The following entries need to be adjusted/removed:
- Duplicates (especially 10.0)
- Move the items to it's proper categories (especially if they are from a previous expansion)
- All the knowledge items are already covered under item spell "Studying", there is no need to add them
- Tomes: are they not working implicitly? (e.g. Dusty Centaur Tome)
- Diaries, Carved and all the other stuff dropped by Doomshadow is best added via item spell, not as single item.
- `--From Comments`  is generally unsorted and needs cleanup

**Comment by cont1nuity** [comment]
Likely handled by #26
