### ISSUE TITLE
Lockbox error when I'm on my rogue

### ISSUE THREAD

**Issue by MoDrogon** [cont1nuity/new-openables-continued#28]
23x NOP/nop-core.lua:502: bad argument #1 to 'gsub' (string expected, got table)

[string "=[C]"]: in function `gsub'

[string "@NOP/nop-core.lua"]:502: in function `CompressText'

[string "@NOP/nop-button.lua"]:340: in function `ButtonShow'

[string "@NOP/nop-item.lua"]:419: in function `ItemShow'

[string "@NOP/nop-item.lua"]:477: in function `?'

[string "@WeakAuras/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

 

Locals:

(*temporary) = <table> {

 castTime = 1500

 name = "Pick Lock"

 minRange = 0

 originalIconID = 136058

 iconID = 136058

 maxRange = 5

 spellID = 1804

}

(*temporary) = "

"

(*temporary) = "/n"

(*temporary) = "string expected, got table"

**Comment by cont1nuity** [comment]
You seem to be on an older version. Could you please update?

**Comment by cont1nuity** [comment]
Should be fixed with the next version.
