### ISSUE TITLE
Element particles

### ISSUE THREAD

**Issue by yoshimo** [cont1nuity/new-openables-continued#3]
https://www.wowhead.com/item=190315/rousing-earth
https://www.wowhead.com/item=190322/rousing-order
https://www.wowhead.com/item=190330/rousing-decay
https://www.wowhead.com/item=190328/rousing-frost
https://www.wowhead.com/item=190326/rousing-air

10x of each can be combined to the awakened version.

**Comment by cont1nuity** [comment]
I have not added these on purpose, as both are used as baseline crafting reagents.
