### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yoshimo** [cont1nuity/new-openables-continued#5]
https://www.wowhead.com/item=201437/slumbering-dream-fragment
https://www.wowhead.com/item=201779/merithras-blessing

https://www.wowhead.com/item=194088/ohuna-companion-color-dark
https://www.wowhead.com/item=194089/bakar-companion-color-orange
https://www.wowhead.com/item=194091/bakar-companion-color-golden-brown
https://www.wowhead.com/item=194094/bakar-companion-color-black

**Comment by cont1nuity** [comment]
Thank you. Added the other colors as well.
